# Generated by Django 5.1.7 on 2025-12-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_category_product_description_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('accessories', 'Accessories')], max_length=100),
        ),
    ]
