# Generated by Django 5.1.5 on 2025-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_rename_product_cartitem_product_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
